[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["cd forex_platform && python manage.py collectstatic --noinput --settings=forex_platform.settings"]

[start]
cmd = "cd forex_platform && python manage.py migrate --settings=forex_platform.settings && gunicorn forex_platform.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
