services:
  - type: web
    name: forexplatform-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: USE_REDIS
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,localhost"
      - key: FOREX_CACHE_TTL
        value: "300"
      - key: DATABASE_URL
        fromDatabase:
          name: forexplatform-db
          property: connectionString

databases:
  - name: forexplatform-db
    plan: free
    databaseName: forex_db
    user: forex_user
