# Generated by Django 4.2.30 on 2026-05-13 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('reserve', 'Reserve'), ('release', 'Release'), ('fee', 'Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=4, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('reserved_balance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('source_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('destination_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('applied_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fee_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tier', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('destination_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='core.currency')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('recipient_transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_received', to='transfers.transaction')),
                ('recipient_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='transfers.wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender_transaction', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_sent', to='transfers.transaction')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='transfers.wallet')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='core.currency')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transfers.wallet'),
        ),
    ]
