# Generated by Django 4.2.30 on 2026-05-13 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0)),
                ('priority', models.IntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avg_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('data_points', models.IntegerField(default=0)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_from', to='core.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_to', to='core.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('business_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('margin', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('sources', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='core.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='core.currency')),
            ],
            options={
                'indexes': [models.Index(fields=['from_currency', 'to_currency'], name='forex_excha_from_cu_b25153_idx')],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
